FROM node:16-alpine as build

WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY .eslintrc.json .eslintrc.json
COPY tsconfig.production.json tsconfig.production.json
COPY ./src/ ./src/

RUN npm run build

FROM node:16-alpine

ENV NODE_ENV production

WORKDIR app

COPY package.json .
COPY package-lock.json .

RUN npm ci --production

COPY --from=build /usr/src/app/dist ./dist

EXPOSE 41234/udp
EXPOSE 20777/udp
