name: 'reviewdog'

on: [pull_request]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'sim-racing-producer/package-lock.json'
    - run: npm ci
      working-directory: sim-racing-producer
    - run: npm run test:ci
      working-directory: sim-racing-producer
    - run: npm run typescript
      working-directory: sim-racing-producer

  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'
          workdir: 'sim-racing-producer'

